CREATE TABLE order_outbox_events (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    event_id VARCHAR(128) NOT NULL,
    order_id BIGINT UNSIGNED NOT NULL,
    aggregate_key VARCHAR(64) NOT NULL COMMENT 'Kafka key=order_no',
    event_type VARCHAR(100) NOT NULL,
    schema_version INT UNSIGNED NOT NULL,
    payload JSON NOT NULL,
    status TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '1=pending, 2=published',
    attempts INT UNSIGNED NOT NULL DEFAULT 0,
    next_attempt_at DATETIME(3) NOT NULL,
    claimed_by VARCHAR(128) NULL,
    claim_until DATETIME(3) NULL,
    last_error_code VARCHAR(64) NULL,
    published_at DATETIME(3) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_order_outbox_event_id (event_id),
    KEY idx_order_outbox_due (status, next_attempt_at, claim_until, id),
    KEY idx_order_outbox_order_id (order_id),
    CONSTRAINT fk_order_outbox_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,
    CONSTRAINT chk_order_outbox_status CHECK (status IN (1, 2)),
    CONSTRAINT chk_order_outbox_schema_version CHECK (schema_version > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
